Repository FundImpact/fundimpact-frontend, pull requests merged in 2020-09, with the labels that each got.

#108 Project cards changes
  src/components/Dasboard/Cards/FundStatus/FundStatus.tsx
  src/components/Dasboard/Cards/Impact/Impact.tsx
Labels: enhancement

#107 Feature/grant period
  package-lock.json
  package.json
  src/App.tsx
  src/components/Budget/BudgetCategory/BudgeCategory.tsx
  src/components/Dasboard/Table/DashboardTableContainer.tsx
  src/components/FormDialog/FormDialog.tsx
  src/components/Forms/GrantPeriod/GranPeriod.tsx
  src/components/Forms/GrantPeriod/dateRange.tsx
  src/components/GrantPeriod/GrantPeriod.tsx
  src/components/Table/Deliverable/Deliverable.tsx
  src/components/Table/GrantPeriod/GrantPeriodTable.tsx
  src/graphql/grantPeriod/mutation.tsx
  src/graphql/grantPeriod/query.tsx
  src/hooks/useLazyQueryCustom/uselazyQueryCustom.tsx
  src/models/grantPeriod/grantPeriodDialog.ts
  src/models/grantPeriod/grantPeriodForm.ts
  src/utils/jsonUtils.ts
Labels: feature

#110 Deliverable sub tablefixes
  README.md
  src/components/Table/Deliverable/Deliverable.tsx
  src/components/Table/Deliverable/DeliverableTrackLine.tsx
  src/components/Table/FICollapseTable.tsx
  src/components/Table/FITable.tsx
Labels: bug

#112 grant period select and cache update bug fixed
  src/components/Forms/GrantPeriod/GranPeriod.tsx
  src/components/GrantPeriod/GrantPeriod.tsx
  src/graphql/Budget/index.tsx
  src/utils/testMock.json
Labels: bug

#127 Implemented Multilingual functionality
  package-lock.json
  package.json
  src/compiled-lang/en.json
  src/compiled-lang/hi.json
  src/components/Budget/BudgetLineitem/BudgetLineItem.tsx
  src/components/Budget/BudgetTarget/BudgetTarget.tsx
  src/components/Deliverable/DeliverableTarget.tsx
  src/components/Deliverable/DeliverableTrackline.tsx
  src/components/Deliverable/DeliverableTracklineDonor.tsx
  src/components/Deliverable/DeliverableUnit.tsx
  src/components/Donor/Donor.tsx
  src/components/Forms/BasicDetailsForm/BasicDetailsForm.tsx
  src/components/Forms/GrantPeriod/BasicDateRangePicker.tsx
  src/components/Forms/GrantPeriod/GranPeriod.tsx
  src/components/Forms/GrantPeriod/dateRange.tsx
  src/components/Forms/GrantPeriod/newPicker.tsx
  src/components/Forms/Login/LoginForm.test.tsx
  src/components/Forms/Login/LoginForm.tsx
  src/components/Impact/ImpactUnitDialog/ImpaceUnitDialog.tsx
  src/components/Impact/impactTarget.tsx
  src/components/Impact/impactTrackLine.tsx
  src/components/Impact/impactTracklineDonor.tsx
  src/components/Placeholders/README.md
  src/components/Placeholders/placeholder.tsx
  src/components/Placeholders/placeholders.jsonc
  src/components/Project/Project.tsx
  src/index.tsx
  src/lang/en.json
  src/lang/hi.json
  src/models/index.ts
  src/pages/Landing/Landing.tsx
  src/pages/Login/Login.test.tsx
  src/pages/Signup/BasicDetailsForm.test.tsx
  src/utils/signup.util.tsx
  tsconfig.json
Labels: enhancement

#137 Documentation for directories
  src/compiled-lang/README.md
  src/contexts/README.md
  src/graphql/README.md
  src/lang/README.md
  src/models/README.md
  src/pages/README.md
  src/utils/README.md
Labels: documentation

#144 Feature/user access management
  src/models/access/modules.jsonc
  src/utils/access/README.md
  src/utils/access/accessChecker.ts
  src/utils/access/index.ts
  src/utils/access/module.interface.ts
  src/utils/access/modules.list.ts
  src/utils/access/modules/README.md
  src/utils/access/modules/budget/actions.ts
  src/utils/access/modules/budget/budget.module.ts
  src/utils/access/modules/deliverables/actions.ts
  src/utils/access/modules/deliverables/deliverable.module.ts
  src/utils/access/modules/impact/actions.ts
  src/utils/access/modules/impact/impact.module.ts
Labels: feature

#140 Added ability to set theme based on user data
  src/components/FilterList/FilterListContainer.tsx
  src/components/FilterList/FilterListView.tsx
  src/components/FilterList/index.tsx
  src/components/Table/Budget/BudgetLineItemTable/__test__/BudgetLineitemTable.test.tsx
  src/components/Table/Budget/BudgetTargetTable/BudgetTargetTableView.tsx
  src/components/Table/Budget/BudgetTargetTable/__test__/BudgetTargetTable.test.tsx
  src/components/Table/BudgetCategoryTable/BudgetCategoryTableView.tsx
  src/components/Table/DeliverableCategoryTable/DeliverableCategoryTableView.tsx
  src/components/Table/DeliverableCategoryTable/__test__/DeliverableCategoryTable.test.tsx
  src/components/Table/FICollapseTable.tsx
  src/components/Table/FITable.tsx
  src/components/Table/Impact/__test__/impactTables.test.tsx
  src/components/Table/Impact/impactTrackline.tsx
  src/components/Table/ImpactCategoryTable/ImpactCategoryTableContainer.tsx
  src/config/routes.tsx
  src/contexts/notificationContext.tsx
  src/contexts/uiContext.tsx
  src/index.tsx
  src/models/userProvider.ts
  src/pages/settings/ImpactMaster/ImpactMasterView.tsx
  src/pages/settings/donor/container.tsx
Labels: feature

#152 Update the broken link in documentation
  src/utils/access/README.md
Labels: documentation
